# Continuous queries
## Common
CREATE CONTINUOUS QUERY "byUid_24h" ON "telemetry" RESAMPLE EVERY 6h BEGIN SELECT distinct("uid") AS "uid" INTO "byUid_24h" FROM "telemetry" GROUP BY time(24h),uid,status,install_version END
#CREATE CONTINUOUS QUERY "byVersion_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT distinct("uid") AS "uid" INTO "byUid_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "by_country_24h" ON "telemetry" RESAMPLE EVERY 6h BEGIN SELECT distinct("uid") AS "uid" INTO "by_country_24h" FROM "telemetry" GROUP BY time(24h),country,country_isocode,uid,status END
CREATE CONTINUOUS QUERY "pods_containers_24h" ON "telemetry" RESAMPLE EVERY 6h BEGIN SELECT last("container_total") AS "containers", last("project_pod_total") AS "pods" INTO "pods_containers_24h" FROM "telemetry" GROUP BY time(24h),uid,status END

## Records v1
CREATE CONTINUOUS QUERY "orchestrators_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("orch_kubernetes") AS "kubernetes", last("orch_mesos") AS "mesos", last("orch_swarm") AS "swarm", last("orch_windows") AS "windows", last("orch_cattle") AS "cattle" INTO "orchestrators_24h" FROM "telemetry" WHERE record_version = '1' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "services_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("service_total") AS "total", last("service_active") AS "active" INTO "services_24h" FROM "telemetry" WHERE record_version = '1' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "stacks_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("stack_total") AS "total", last("stack_active") AS "active", last("stack_from_catalog") AS "from_catalog" INTO "stacks_24h" FROM "telemetry" WHERE record_version = '1' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "hosts_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("host_active") AS "host", last("host_cpu_cores_total") AS "cpu", last("host_mem_mb_total") AS "memory" INTO "hosts_24h" FROM "telemetry" WHERE record_version = '1' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "containers_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("container_total") AS "total", last("container_running") AS "running" INTO "containers_24h" FROM "telemetry" WHERE record_version = '1' GROUP BY time(24h),uid,status END


## Records v2
CREATE CONTINUOUS QUERY "v2_clusters_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("cluster_total") AS "total", last("cluster_active") AS "active", last("cluster_cpu_total") AS "cpu", last("cluster_driver_aks") AS "cluster_aks", last("cluster_driver_eks") AS "cluster_eks", last("cluster_driver_imported") AS "cluster_imported", last("cluster_driver_gke") AS "cluster_gke", last("cluster_driver_rke") AS "cluster_rke", last("cluster_mem_mb_total") AS "mem_mb", last("cluster_namespace_total") AS "namespaces", last("cluster_namespace_from_catalog") AS "namespace_from_catalog" INTO "v2_clusters_24h" FROM "telemetry" WHERE record_version = '2' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "v2_projects_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("project_total") AS "total", last("project_namespace_total") AS "namespaces", last("project_namespace_from_catalog") AS "namespace_from_catalog", last("project_pod_total") AS "pods", last("project_workload_total") AS "workloads" INTO "v2_projects_24h" FROM "telemetry" WHERE record_version = '2' GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "v2_nodes_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("node_total") AS "total", last("node_active") AS "active", last("node_from_template") AS "from_template", last("node_driver_azure") AS "node_azure", last("node_driver_ec2") AS "node_ec2", last("node_driver_do") AS "node_do", last("node_driver_openstack") AS "node_openstack", last("node_driver_vsphere") AS "node_vsphere", last("node_imported") AS "imported", last("node_mem_mb_total") AS "mem_mb", last("node_role_controlplane") AS "controlplane", last("node_role_etcd") AS "etcd", last("node_role_worker") AS "worker" INTO "v2_nodes_24h" FROM "telemetry" WHERE record_version = '2' GROUP BY time(24h),uid,status END
