# Continuous queries
CREATE CONTINUOUS QUERY "containers_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("container_total") AS "total", last("container_running") AS "running" INTO "containers_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "byUid_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT distinct("uid") AS "uid" INTO "byUid_24h" FROM "telemetry" GROUP BY time(24h),uid,status,install_version END
CREATE CONTINUOUS QUERY "byVersion_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT distinct("uid") AS "uid" INTO "byUid_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "by_country_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT distinct("uid") AS "uid" INTO "by_country_24h" FROM "telemetry" GROUP BY time(24h),country,country_isocode,uid,status END
CREATE CONTINUOUS QUERY "orchestrators_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("orch_kubernetes") AS "kubernetes", last("orch_mesos") AS "mesos", last("orch_swarm") AS "swarm", last("orch_windows") AS "windows", last("orch_cattle") AS "cattle" INTO "orchestrators_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "services_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("service_total") AS "total", last("service_active") AS "active" INTO "services_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "stacks_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("stack_total") AS "total", last("stack_active") AS "active", last("stack_from_catalog") AS "from_catalog" INTO "stacks_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
CREATE CONTINUOUS QUERY "hosts_24h" ON "telemetry" RESAMPLE EVERY 12h BEGIN SELECT last("host_active") AS "host", last("host_cpu_cores_total") AS "cpu", last("host_mem_mb_total") AS "memory" INTO "hosts_24h" FROM "telemetry" GROUP BY time(24h),uid,status END
