apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: telemetry-client
  name: telemetry-client
  namespace: telemetry
spec:
  selector:
    matchLabels:
      app: telemetry-client
  template:
    metadata:
      labels:
        app: telemetry-client
    spec:
      containers:
        - name: telemetry-client
          image: $(TELEMETRY_IMAGE)
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 1000m
          envFrom:
            - configMapRef:
                name: telemetry-client
          env:
            - name: TELEMETRY_INTERVAL
              value: "1m"
            - name: CATTLE_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: telemetry
                  key: api_key
          args:
            - client
